name: SortingHat
description: SorteerHoed Informatica Leiden
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite:
  rflutter_alert: ^2.0.4
  charts_flutter: ^0.11.0
  path_provider: ^2.0.3
  cupertino_icons: ^1.0.0
  firebase_core: "^1.6.0"
  cloud_firestore: "^2.5.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/hsl_logo.png

  fonts:
      - family: AlfaSlabOne
        fonts:
          - asset: assets/fonts/AlfaSlabOne-Regular.ttf
      - family: BebasNeue
        fonts:
          - asset: assets/fonts/BebasNeue-Regular.ttf
